---
title: "DASHBOARD ACOES - NIVIANE ALVES"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyquant)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)

prices <- c(
  "ARZZ3", "TIMS3", "CRFB3", "BBDC4", "CIEL3",
  "HAPV3", "PETR4", "RAIZ4", "SANB11", "SUZB3"
) %>%
  paste0(".SA") %>%
  tq_get(get = "stock.prices", from = " 2010-01-01") %>%
  mutate(symbol = sub(".SA", "", symbol))
tabela_periodo <- data.frame(
  periodo = c("30 dias", "6 Meses", "1 Ano", "10 Anos"),
  dias = c(30, 182, 365, 3650)
)
tabela_periodo1 <- data.frame(
  periodo1 = c("30 dias", "6 Meses", "1 Ano", "10 Anos"),
  dias = c(30, 182, 365, 3650)
  
)
colours = c(
  "ARZZ3" = "blue", "TIMS3" = "black", "CRFB3" = "red", "BBDC4" = "cyan", "CIEL3" = "pink",
  "HAPV3" = "yellow", "PETR4" = "green", "RAIZ4" = "purple", "SANB11" = "gray", "SUZB3" = "orange"
  )
```

# Tendências

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(
  "acao", label = "Escolha sua Ação",
  choices = c(
    "ARZZ3", "TIMS3", "CRFB3", "BBDC4", "CIEL3",
    "HAPV3", "PETR4", "RAIZ4", "SANB11", "SUZB3"
  )
)
selectInput(
  "periodo", label = "Escolha o período",
  choices = c("30 dias", "6 Meses", "1 Ano", "10 Anos")
)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Tendência

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>%
    filter(date >= periodo, symbol == input$acao) %>%
    ggplot() +
    aes(x = date, y = adjusted, color = symbol) +
    geom_line() +
    scale_color_manual(values = colours) +
    labs(x = "", y = "Cotação") +
    ggtitle(label = input$acao) +
    theme(
      panel.background = element_blank(),
      plot.title = element_text(size = 22),
      legend.position = "none"
    )
})
```

### Todas as tendências

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>%
    filter(date >= periodo) %>%
    ggplot() +
    aes(x = date, y = adjusted, color = symbol) +
    geom_line(linewidth = 0.5) +
    scale_color_manual(values = colours) +
    labs(x = "", y = "Cotação", color = "Ação") +
    theme(panel.background = element_blank())
})
```

# Cotações

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(
  "acao1", label = "Escolha sua Ação",
  choices = c(
    "ARZZ3", "TIMS3", "CRFB3", "BBDC4", "CIEL3",
    "HAPV3", "PETR4", "RAIZ4", "SANB11", "SUZB3"
  )
)
selectInput(
  "periodo1", label = "Escolha o período",
  choices = c("30 dias", "6 Meses", "1 Ano", "10 Anos")
)
```


Column {data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  periodo1 <- Sys.Date() - filter(tabela_periodo1, periodo1 == input$periodo1)$dias
  
  prices %>%
    filter(date >= periodo1, symbol == input$acao1) %>%
    mutate(across(where(is.double), round, digits = 2)) %>%
    arrange(desc(date)) %>%
    rename(
      Acao = symbol,
      Data = date,
      Abertura = open,
      Maximo = high,
      Minimo = low,
      Fechamento = close,
      Volume = volume,
      Ajustado = adjusted
    ) %>%
    datatable(rownames = FALSE)
})
```
```

